export const WebSocketEventTypes = {
  MESSAGE_CREATED: 'MESSAGE_CREATED',
  MESSAGE_EDITED: 'MESSAGE_EDITED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',
  USER_TYPING: 'USER_TYPING',
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  ROOM_USER_ONLINE: 'ROOM_USER_ONLINE',
  ROOM_USER_OFFLINE: 'ROOM_USER_OFFLINE',
  NOTIFICATION: 'NOTIFICATION',
};

export const WebSocketMessageTypes = {
  USER_TYPING: 'USER_TYPING',
  PONG: 'PONG',
};
